import { config } from 'dotenv';
import { writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';
import { existsSync } from 'fs';

// Load environment variables
config();

const CONVERSATION_SAVE_DIR = process.env.CONVERSATION_SAVE_DIR;
const CONVERSATION_SAVE_ENABLED = process.env.CONVERSATION_SAVE_ENABLED !== 'false'; // Default true

export class ConversationSaver {
    private saveDir: string | undefined;
    private enabled: boolean;

    constructor() {
        this.saveDir = CONVERSATION_SAVE_DIR;
        this.enabled = CONVERSATION_SAVE_ENABLED && !!this.saveDir;

        if (this.enabled && this.saveDir) {
            console.log(`[ConversationSaver] ✅ Enabled`);
            console.log(`[ConversationSaver] 📁 Save directory: ${this.saveDir}`);
        } else {
            console.log('[ConversationSaver] ⚠️  Disabled (not configured)');
        }
    }

    /**
     * Save a conversation to Obsidian vault
     */
    async saveConversation(
        question: string,
        answer: string,
        userName: string = 'User'
    ): Promise<boolean> {
        if (!this.enabled || !this.saveDir) {
            return false;
        }

        try {
            const timestamp = new Date();
            const markdown = this.generateMarkdown(question, answer, userName, timestamp);
            const filename = this.generateFilename(timestamp);
            const filepath = join(this.saveDir, filename);

            // Ensure directory exists
            await this.ensureDirectory(this.saveDir);

            // Write file
            await writeFile(filepath, markdown, 'utf-8');

            console.log(`[ConversationSaver] ✅ Saved to: ${filename}`);
            return true;
        } catch (error) {
            console.error(`[ConversationSaver] ❌ Failed to save: ${error}`);
            return false;
        }
    }

    /**
     * Generate markdown content with YAML frontmatter
     */
    private generateMarkdown(
        question: string,
        answer: string,
        userName: string,
        timestamp: Date
    ): string {
        const dateStr = this.formatDate(timestamp);
        const timeStr = this.formatTime(timestamp);

        return `---
created: ${dateStr} ${timeStr}
source: Telegram Bot
user: ${userName}
tags: [telegram, 对话, inkbrain]
---

# Telegram 对话 - ${dateStr} ${timeStr.substring(0, 5)}

## 问题

${question}

## 回答

${answer}

---
*Generated by InkBrain Telegram Bot*
`;
    }

    /**
     * Generate filename with timestamp
     */
    private generateFilename(timestamp: Date): string {
        const dateStr = this.formatDate(timestamp).replace(/-/g, '');
        const timeStr = this.formatTime(timestamp).replace(/:/g, '');
        return `Telegram_对话_${dateStr}_${timeStr}.md`;
    }

    /**
     * Format date as YYYY-MM-DD
     */
    private formatDate(date: Date): string {
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    /**
     * Format time as HH:mm:ss
     */
    private formatTime(date: Date): string {
        const hours = String(date.getHours()).padStart(2, '0');
        const minutes = String(date.getMinutes()).padStart(2, '0');
        const seconds = String(date.getSeconds()).padStart(2, '0');
        return `${hours}:${minutes}:${seconds}`;
    }

    /**
     * Ensure directory exists
     */
    private async ensureDirectory(dir: string): Promise<void> {
        if (!existsSync(dir)) {
            await mkdir(dir, { recursive: true });
            console.log(`[ConversationSaver] 📁 Created directory: ${dir}`);
        }
    }

    /**
     * Check if saver is enabled
     */
    isEnabled(): boolean {
        return this.enabled;
    }
}

/**
 * Convenience function to create a conversation saver
 */
export function createConversationSaver(): ConversationSaver {
    return new ConversationSaver();
}
